### ISSUE TITLE
Node JS ｢wdm｣: Failed to compile.

### ISSUE THREAD

**Issue by Adrianmbugua** [LearnWebCode/university-static#15]
on Lesson 7 work flow and automation , I run the command npm run devFast , I got the following error 

`ERROR in ./js/scripts.js
Module not found: Error: Can't resolve '../css/style.css' in 'C:\xampp\htdocs\uni\wp-content\themes\fictional-university-theme\js'
 @ ./js/scripts.js 1:0-26`

is there something missing or i'm I doing something wrong

**Comment by umer310** [comment]
`i ｢wds｣: Project is running at http://localhost:3000/
i ｢wds｣: webpack output is served from http://localhost:3000/
i ｢wds｣: Content not from webpack is served from C:\Users\umera\Local Sites\gutenberg\app\public\wp-content\themes\fictional-university-theme
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (C:\Users\umera\Local Sites\gutenberg\app\public\wp-content\themes\fictional-university-theme\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\umera\Local Sites\gutenberg\app\public\wp-content\themes\fictional-university-theme\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\umera\Local Sites\gutenberg\app\public\wp-content\themes\fictional-university-theme\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\umera\Local Sites\gutenberg\app\public\wp-content\themes\fictional-university-theme\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\umera\Local Sites\gutenberg\app\public\wp-content\themes\fictional-university-theme\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\umera\Local Sites\gutenberg\app\public\wp-content\themes\fictional-university-theme\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\umera\Local Sites\gutenberg\app\public\wp-content\themes\fictional-university-theme\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\Users\umera\Local Sites\gutenberg\app\public\wp-content\themes\fictional-university-theme\node_modules\loader-runner\lib\LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
`
